
name: "Newman Tests"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run API Tests
        run: newman run "ReqRes_coll.json" -e ReqRes_env.json
